x-raft: &raft
  build: .
  restart: always
  healthcheck:
    test: ["CMD", "/keel", "healthcheck", "/readyz"]
    interval: 10s
    timeout: 3s
    retries: 3
    start_period: 5s

x-env: &env
  PORT: "7000"
  HTTP_PORT: ":8080"
  DATA_DIR: "/data"
  LOG_LEVEL: "${LOG_LEVEL:-info}"
  PEERS: "1=raft-1:7000,2=raft-2:7000,3=raft-3:7000,4=raft-4:7000,5=raft-5:7000"
  HTTP_PEERS: "1=raft-1:8080,2=raft-2:8080,3=raft-3:8080,4=raft-4:8080,5=raft-5:8080"

services:
  raft-1:
    <<: *raft
    volumes:
      - raft-one-data:/data
    environment:
      <<: *env
      ID: "1"
    ports:
      - "8081:8080"

  raft-2:
    <<: *raft
    volumes:
      - raft-two-data:/data
    environment:
      <<: *env
      ID: "2"
    ports:
      - "8082:8080"

  raft-3:
    <<: *raft
    volumes:
      - raft-three-data:/data
    environment:
      <<: *env
      ID: "3"
    ports:
      - "8083:8080"

  raft-4:
    <<: *raft
    volumes:
      - raft-four-data:/data
    environment:
      <<: *env
      ID: "4"
    ports:
      - "8084:8080"

  raft-5:
    <<: *raft
    volumes:
      - raft-five-data:/data
    environment:
      <<: *env
      ID: "5"
    ports:
      - "8085:8080"

volumes:
  raft-one-data:
  raft-two-data:
  raft-three-data:
  raft-four-data:
  raft-five-data:

networks:
  default:
    name: raft-network
